name: The World of Faeries
favicon: null
layout_spectrum: 0.4451805017888546
typography_spectrum: 0.9331970543134958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.43329979688860476
  lightness: 0.7423139959573746
  saturation: 0.3435954130254686
  rhythmicContrast: 0.4836697746068239
purpose: []
